"""add classroom table

Revision ID: 032731ea5b82
Revises: 7e9d5b5a111b
Create Date: 2022-05-13 14:15:16.319365

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '032731ea5b82'
down_revision = '7e9d5b5a111b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.String(), nullable=False),
                    sa.Column('capacity', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom')
    # ### end Alembic commands ###
