"""add type_schedule_item table

Revision ID: 14bdb0215f66
Revises: 1569fa621c91
Create Date: 2022-05-14 02:30:15.136349

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14bdb0215f66'
down_revision = '1569fa621c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_schedule_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_schedule_item')
    # ### end Alembic commands ###
