"""add group table

Revision ID: 1569fa621c91
Revises: 6c3e869a4fd9
Create Date: 2022-05-14 02:15:31.990625

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1569fa621c91'
down_revision = '6c3e869a4fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subgroup',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subgroup')
    op.drop_table('group')
    # ### end Alembic commands ###
