"""add week table

Revision ID: 7e9d5b5a111b
Revises: 89d7b08f883e
Create Date: 2022-05-13 13:37:23.821272

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7e9d5b5a111b'
down_revision = '89d7b08f883e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week')
    # ### end Alembic commands ###
