"""add bell table

Revision ID: 89d7b08f883e
Revises: 
Create Date: 2022-05-12 00:19:10.736366

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89d7b08f883e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bell',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_beg', sa.String(), nullable=False),
                    sa.Column('time_end', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bell')
    # ### end Alembic commands ###
