"""add schedule_item table

Revision ID: a973fc07ac9a
Revises: 14bdb0215f66
Create Date: 2022-05-14 02:37:55.465333

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a973fc07ac9a'
down_revision = '14bdb0215f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('classroom_id', sa.Integer(), nullable=False),
                    sa.Column('bell_id', sa.Integer(), nullable=False),
                    sa.Column('week_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('subgroup_id', sa.Integer(), nullable=True),
                    sa.Column('type_schedule_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bell_id'], ['bell.id'], ),
                    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroup.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
                    sa.ForeignKeyConstraint(['type_schedule_item_id'], ['type_schedule_item.id'], ),
                    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_item')
    # ### end Alembic commands ###
