"""date in schedule_item table

Revision ID: afc6a666c4e4
Revises: b6286c998945
Create Date: 2022-05-20 18:01:38.066562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'afc6a666c4e4'
down_revision = 'b6286c998945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_item', sa.Column('date', sa.Date(), nullable=True))
    op.execute("UPDATE \"schedule_item\" SET date = now()")
    op.alter_column('schedule_item', 'date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_item', 'date')
    # ### end Alembic commands ###
