"""add check_collision in schedule item

Revision ID: d2a063c3f2de
Revises: 951a6b738ad0
Create Date: 2022-06-11 16:18:07.889597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a063c3f2de'
down_revision = '951a6b738ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_item', sa.Column('check_collision', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_item', 'check_collision')
    # ### end Alembic commands ###
